# Generated by Django 2.0.7 on 2021-03-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [

    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=150)),
                ('email', models.CharField(default=' ', max_length=70)),
                ('password', models.CharField(default=' ', max_length=70)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.game')),
                ('current_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.game')),
                ('inventory', models.IntegerField(default=0)),
                ('backorder', models.IntegerField(default=0)),
                ('downstream_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Player.player', related_name="previous_player")),
                ('upstream_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Player.player', related_name="next_player")),
            ],
        ),
    ]
