# Generated by Django 3.1.7 on 2021-03-09 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
        ('Instructor', '0002_auto_20210309_1839'),
        ('Player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_game',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='Game.game'),
        ),
        migrations.AlterField(
            model_name='player',
            name='downstream_player',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_player', to='Player.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.AutoField(auto_created=True, default=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructor.instructor'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='player',
            name='upstream_player',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_player', to='Player.player'),
        ),
    ]
