# Generated by Django 2.0.7 on 2021-03-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=150)),
                ('email', models.CharField(default=' ', max_length=70)),
                ('password', models.CharField(default=' ', max_length=70)),
            ],
        ),
    ]
