# Generated by Django 3.1.7 on 2021-04-02 22:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('game_id', models.CharField(default='id', max_length=32, primary_key=True, serialize=False)),
                ('session_length', models.IntegerField(default=26)),
                ('distributer_present', models.BooleanField(default=True)),
                ('wholesaler_present', models.BooleanField(default=True)),
                ('holding_cost', models.FloatField(default=1)),
                ('backlog_cost', models.FloatField(default=1)),
                ('rounds_completed', models.IntegerField(default=0)),
                ('starting_inventory', models.IntegerField(default=0)),
                ('active_status', models.BooleanField(default=True)),
                ('info_sharing', models.BooleanField(default=False)),
                ('info_delay', models.IntegerField(default=2)),
                ('demand_id', models.CharField(max_length=32)),
                ('instructor', models.ForeignKey(limit_choices_to={'is_instructor': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemandPattern',
            fields=[
                ('demand_id', models.CharField(default='id', max_length=32, primary_key=True, serialize=False)),
                ('weeks_num', models.IntegerField()),
                ('demands', models.CharField(max_length=128, validators=[django.core.validators.int_list_validator])),
                ('created_by', models.ForeignKey(limit_choices_to={'is_instructor': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
