# Generated by Django 3.1.7 on 2021-04-03 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandpattern',
            old_name='created_by',
            new_name='instructor',
        ),
    ]
