# Generated by Django 3.1.7 on 2021-03-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_auto_20210321_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='backlog_cost',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='holding_cost',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='rounds_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='starting_inventory',
            field=models.IntegerField(default=0),
        ),
    ]
