# Generated by Django 3.1.7 on 2021-04-23 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Game', '0002_auto_20210423_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week',
            old_name='status',
            new_name='completed_status',
        ),
        migrations.RemoveField(
            model_name='game',
            name='demand_id',
        ),
        migrations.AddField(
            model_name='game',
            name='demand',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gamedemand', to='Game.demandpattern'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demandpattern',
            name='demand_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='week',
            name='order',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterUniqueTogether(
            name='playergame',
            unique_together={('user_id', 'game_id')},
        ),
    ]
