# Generated by Django 3.1.7 on 2021-04-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0004_auto_20210423_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='distributer_present',
            new_name='distributor_present',
        ),
    ]
