# Generated by Django 3.1.7 on 2021-04-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0004_auto_20210407_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergame',
            name='game_id',
            field=models.CharField(default='no-game', max_length=32),
        ),
    ]
