# Generated by Django 3.1.7 on 2021-04-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0005_auto_20210423_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='completed_status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='cost',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='demand',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='incoming',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='inventory',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='order',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='outgoing',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='week_num',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
