# Generated by Django 3.1.7 on 2021-04-11 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Game', '0005_auto_20210407_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandpattern',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'is_instructor': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playergame',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Weeks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(default='no-game', max_length=32)),
                ('week_num', models.IntegerField(default=1)),
                ('inventory', models.IntegerField(default=0)),
                ('demand', models.IntegerField(default=0)),
                ('incoming', models.IntegerField(default=0)),
                ('outgoing', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
