# Generated by Django 3.1.7 on 2021-04-23 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0006_auto_20210423_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergame',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playergame',
            name='game_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gameroles', to='Game.game'),
        ),
    ]
