# Generated by Django 3.1.7 on 2021-04-23 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0007_auto_20210424_0124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playergame',
            old_name='ordered',
            new_name='order_status',
        ),
    ]
