# Generated by Django 3.1.7 on 2021-04-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0008_auto_20210424_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='backlog',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
